// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"SlowText","status":true,"description":"This plugin makes rpgmaker draw text at a slower speed.","parameters":{"Text Speed":"2"}},
{"name":"GALV_BalloonSoundEffects","status":true,"description":"Set sound effects to play whenever balloons are shown above characters","parameters":{"Exclamation":"Flash1,50,150","Question":"Jump1,50,120","Music Note":"Up3,50,150","Heart":"Sound2,80,150","Anger":"Push,80,150","Sweat":"Miss,80,150","Cobweb":"Wind4,80,150","Silence":"","Light Bulb":"Load,80,150","Zzz":"","User-defined 1":"Item1,80,150","User-defined 2":"Item2,80,150","User-defined 3":"Item3,80,150","User-defined 4":"Reflection,80,150","User-defined 5":"Reflection,80,100"}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"0","Offset Y":"60","Width":"240","Background":"1"}},
{"name":"Continue","status":true,"description":"","parameters":{}}
];
